#+TITLE: PHP-Programm-Guide für die 8D
#+AUTHOR: Peter Ostertag
#+DATE: Schuljahr 2019/20
#+LANGUAGE: de
#+OPTIONS: ':t
#+OPTIONS: toc:nil num:0
#+STARTUP: inlineimages

* Vorbemerkung für Maturant*innen:

In diesem Repository sind auch einige Programme abgelegt, die nicht für diese Matura relevant sind!
Orientiert euch einfach am Inhaltsverzeichnis!

Zum Starten muss man diese Programme immer im Serververzeichnis abspeichern (bei Apache für Windows ist das meist =C:\apache2\htdocs=).

Damit der Server das PHP-Skript ausführt, muss man die Datei auch über den lokalen Server ("localhost") aufrufen: also nicht mit Doppelklick auf die Datei, sondern mit =http://localhost/Datei.php= in der Adresszeile eines Browsers.

* Einfache Übungsbeispiele

- [[glueck2.php][Glückszahl ausgeben]]: random, isset
- Wollmützen bestellen: hier ist die Aktion auf 2 Dateien aufgeteilt: eine html-Datei mit dem Formular und eine php-Datei mit der Auswertung:
  - [[Bestell1.html][Bestellen (html)]]
  - [[Bestell2.php][Warenkorb]]

* Hashfunktionen
- [[file:hashmich.php][Hash mich!]]

* Merkle-Bäume
Siehe im Skriptum Genaueres zu diesem Thema!

- [[file:MerkleSimple.php][Allereinfachstes Merkle-Programm]]
- Merkle mit Function
- Merkle mit Array



* Cookies

- [[file:CookieSimpel.php][Allereinfachstes Cookieprogramm]]
- [[file:CookieZaehler.php][Zugriffe zählen mit Cookies]]
